# fruits= []
# a=input("Enter fruit name: ")
# fruits.append(a)
# a=input("Enter fruit name: ")
# fruits.append(a)
# a=input("Enter fruit name: ")
# fruits.append(a)
# a=input("Enter fruit name: ")
# fruits.append(a)
# a=input("Enter fruit name: ")
# fruits.append(a)
# a=input("Enter fruit name: ")
# fruits.append(a)
# a=input("Enter fruit name: ")
# fruits.append(a)
# print(fruits)

marks=[]
m1=int(input("Enter the marks: "))
marks.append(m1)
m1=int(input("Enter the marks: "))
marks.append(m1)
m1=int(input("Enter the marks: "))
marks.append(m1)
m1=int(input("Enter the marks: "))
marks.append(m1)
m1=int(input("Enter the marks: "))
marks.append(m1)
m1=int(input("Enter the marks: "))
marks.append(m1)
marks.sort()
print(marks)
